[tool.black]
target_version = ['py310']
include = '\.pyi?$'
line-length = 100
force-exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations/*
    | migrations
    | __init__.py

    # The following are specific to Black, you probably don't want those.
    | blib2to3
    | tests/data
    | profiling
)/
'''

[tool.isort]
profile = "black"
extend_skip_glob = ["**/migrations/*.py"]
skip = "migrations"
multi_line_output = 3
known_django = "django"
known_djangocontrib =" django.contrib"
sections = "FUTURE,STDLIB,DJANGO,DJANGOCONTRIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
py_version=310
filter_files = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "dle.settings"
env_files = "tests/test.env"