Parameters:
  DBTypeParameter:
    Type: String
    Default: "db.t4g.medium"
    AllowedValues:
      - db.t4g.medium
    Description: Default is db.t4g.medium.
  VPCParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vpc_id

Resources:
  globalRxDBSecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Open 5432
      VpcId: !Ref VPCParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: 0.0.0.0/0 

  globalRxDB:
    Type: AWS::RDS::DBInstance
    DependsOn: SearchRxSubnetGroup
    Properties:
      VPCSecurityGroups:
        - !GetAtt "globalRxDBSecGroup.GroupId"
      AllocatedStorage: '60'
      DBInstanceClass: !Ref DBTypeParameter
      DBSubnetGroupName: rds-subnet-group
      Engine: postgres
      MasterUsername: postgres
      MasterUserPassword: fghyucvsafd
    DeletionPolicy: Delete

  SearchRxSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: subnet group for RDS
      DBSubnetGroupName: rds-subnet-group
          SubnetIds: 
            - subnet-0cfa82bd41644a2c5
            - subnet-0112d7b96d708a330
      Tags: 
        - Tag

Outputs:
  globalRxEndpoint:
      Description: "DB Endpoint"
      Value: !GetAtt globalRxDB.Endpoint.Address
