
Parameters:
  RepoName:
    Type: String
    Default: "django"

Resources:
  ecrRepo:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: ecr_repo
      Type: String
      Value: !Ref RepoName

Outputs:
  ecrRepo:
    Description: ECR Repo 
    Value: !Ref ecrRepo
