Parameters:
  DBTypeParameter:
    Type: String
    Default: "db.t4g.medium"
    AllowedValues:
      - db.t4g.medium
    Description: Default is db.t4g.medium.
  VPCParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vpc_id
  subnet1:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /public_subnet_1
  subnet2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /public_subnet_2
  rdsPassword:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rdsPassword




Resources:
  globalRxDBSecGroupdev:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Open 5432
      VpcId: !Ref VPCParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: 0.0.0.0/0

  globalRxDBdev:
    Type: AWS::RDS::DBInstance
    DependsOn: SearchRxSubnetGroupdev
    Properties:
      VPCSecurityGroups:
        - !GetAtt "globalRxDBSecGroupdev.GroupId"
      AllocatedStorage: '60'
      DBInstanceClass: !Ref DBTypeParameter
      DBSubnetGroupName: rds-subnet-groupdev
      Engine: postgres
      MasterUsername: postgres
      MasterUserPassword: !Ref rdsPassword
    DeletionPolicy: Delete

  SearchRxSubnetGroupdev:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: subnet group for RDS
      DBSubnetGroupName: rds-subnet-groupdev
      SubnetIds: 
        - !Ref subnet1
        - !Ref subnet2

  endPointdev:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: db_endpointdev
      Type: String
      Value: !GetAtt globalRxDBdev.Endpoint.Address

Outputs:
  globalRxEndpointdev:
      Description: "DB Endpoint"
      Value: !GetAtt globalRxDBdev.Endpoint.Address