
Resources:
  Repo1:
    Type: AWS::ECR::Repository
    Properties: 
      ImageScanningConfiguration: 
        ScanOnPush: True
      RepositoryName: "django"

  Repo2:
    Type: AWS::ECR::Repository
    Properties: 
      ImageScanningConfiguration: 
        ScanOnPush: True
      RepositoryName: "postgres"
