
Parameters:
  RepoName:
    Type: String
    Default: "django"
Resources:
  Repo1:
    Type: AWS::ECR::Repository
    Properties: 
      ImageScanningConfiguration: 
        ScanOnPush: True
      RepositoryName: !Ref RepoName

Outputs:
  searchRxRepo: !Ref RepoName
