Parameters:
  DBTypeParameter:
    Type: String
    Default: "db.t4g.medium"
    AllowedValues:
      - db.t4g.medium
    Description: Default is db.t4g.medium.
  VPCParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vpc_id
  subnet1:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /public_subnet_1
  subnet2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /public_subnet_2
  subnet2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /public_subnet_2
  rdsPassword:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rds_pword



Resources:
  searchRxDBSecGroupsearch:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Open 5432
      VpcId: !Ref VPCParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: 0.0.0.0/0

  searchRxDBsearch:
    Type: AWS::RDS::DBInstance
    DependsOn: SearchRxSubnetGroupsearch
    Properties:
      VPCSecurityGroups:
        - !GetAtt "searchRxDBSecGroupsearch.GroupId"
      AllocatedStorage: '60'
      DBInstanceClass: !Ref DBTypeParameter
      DBSubnetGroupName: rds-subnet-groupsearch
      Engine: postgres
      MasterUsername: postgres
      MasterUserPassword: !Ref rdsPassword
    DeletionPolicy: Delete

  SearchRxSubnetGroupsearch:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: subnet group for RDS
      DBSubnetGroupName: rds-subnet-groupsearch
      SubnetIds: 
        - !Ref subnet1
        - !Ref subnet2

  endPointsearch:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: rds_endpoint
      Type: String
      Value: !GetAtt searchRxDBsearch.Endpoint.Address

Outputs:
  searchRxEndpointsearch:
      Description: "DB Endpoint"
      Value: !GetAtt searchRxDBsearch.Endpoint.Address
