AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: "m6i.large"
    AllowedValues:
      - t2.micro
      - m5.small
      - m6i.large
    Description: Default is t2.micro.
  ImageIDParameter:
    Type: String
    Default: "ami-005f9685cb30f234b"
    AllowedValues:
      - ami-005f9685cb30f234b
    Description: Amazon Linux AMI.
  KeyIDParameter:
    Type: String
    Default: "CHBC_MAC"
    AllowedValues:
      - CHBC_MAC
  NameParameter:
    Type: String
    Default: "CFN_TEST"
    Description: Value for Name Tag
  EmailParameter:
    Type: String
    Default: "aeg224@g.harvard.edu"
    Description: email for django admin user
  DBTypeParameter:
    Type: String
    Default: "db.t4g.medium"
    AllowedValues:
      - db.t4g.medium
    Description: Default is db.t4g.medium.


Resources:
  NestedStackVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: >-
        https://globalrx.s3.amazonaws.com/deploy_vpc.yaml

  NestedStackECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: >-
        https://globalrx.s3.amazonaws.com/deploy_ecr.yaml

  NestedStackRDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: >-
        https://globalrx.s3.amazonaws.com/deploy_rds.yaml
      Parameters:
        VPCParameter:
          Fn::GetAtt: 
          - NestedStackVPC
          - Outputs.VPC
        DBTypeParameter: !Ref DBTypeParameter
  
  NestedStackEC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: >-
        https://globalrx.s3.amazonaws.com/deploy_ec2.yaml
      Parameters:
        EmailParameter: !Ref EmailParameter
        InstanceTypeParameter: !Ref InstanceTypeParameter
        NameParameter: !Ref NameParameter
        KeyIDParameter: !Ref KeyIDParameter
        ImageIDParameter: !Ref ImageIDParameter
        DBEndpointParameter:
          Fn::GetAtt: 
          - NestedStackRDS
          - Outputs.globalRxEndpoint
        VPCParameter:
          Fn::GetAtt: 
          - NestedStackVPC
          - Outputs.VPC

