# Generated by Django 4.0.2 on 2022-04-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_id", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=8)),
                ("product_name", models.CharField(max_length=255)),
                ("version_date", models.DateField()),
                ("generic_name", models.CharField(max_length=255)),
                ("source_product_number", models.CharField(max_length=255)),
                ("marketer", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DrugLabelDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_id", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=8)),
                ("product_name", models.CharField(max_length=255)),
                ("version_date", models.DateField()),
                ("generic_name", models.CharField(max_length=255)),
                ("source_product_number", models.CharField(max_length=255)),
                ("marketer", models.CharField(max_length=255)),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="LabelProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drug_label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.druglabeldoc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        choices=[
                            ("Indications", "Indications"),
                            ("Contraindications", "Contraindications"),
                            ("Warnings", "Warnings"),
                            ("Pregnancy", "Pregnancy"),
                            ("Posology", "Posology"),
                            ("Interactions", "Interactions"),
                            ("Effects on driving", "Effects on driving"),
                            ("Side effects", "Side effects"),
                            ("Overdose", "Overdose"),
                        ],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                ("section_text", models.TextField()),
                (
                    "label_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.labelproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugLabelRawText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField()),
                (
                    "drug_label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.druglabeldoc",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="druglabeldoc",
            constraint=models.UniqueConstraint(
                fields=("source", "source_product_number", "version_date"),
                name="unique_dl",
            ),
        ),
    ]
