# Generated by Django 4.0.2 on 2023-03-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_druglabel_generic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druglabel',
            name='source',
            field=models.CharField(choices=[('FDA', 'USA - Federal Drug Administration'), ('EMA', 'EU - European Medicines Agency'), ('TGA', 'AU - Therapeutic Goods Administration')], db_index=True, max_length=8),
        ),
    ]
