# Generated by Django 4.0.2 on 2023-04-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_druglabel_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsection',
            name='bert_vector',
            field=models.TextField(null=True),
        ),
    ]
