# Generated by Django 4.2 on 2023-04-13 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_productsection_bert_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='druglabel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='druglabel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
