# Generated by Django 4.2 on 2023-04-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_druglabel_created_at_druglabel_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_parsed', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=400)),
                ('errorType', models.CharField(blank=True, choices=[('version_date_empty', 'Version date empty'), ('version_date_parse', 'Version date parsed failure'), ('pdf_error', 'Failed to parse PDF')], default=None, max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.druglabel')),
            ],
        ),
    ]
