# Generated by Django 4.2 on 2023-04-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_parsingerror'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsingerror',
            old_name='comments',
            new_name='message',
        ),
        migrations.AddField(
            model_name='parsingerror',
            name='source',
            field=models.CharField(blank=True, choices=[('TGA', 'Therapeutic Goods Administration'), ('FDA', 'Food and Drug Administration'), ('EMA', 'European Medicines Agency')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='parsingerror',
            name='errorType',
            field=models.CharField(blank=True, choices=[('version_date_empty', 'Version date empty'), ('version_date_parse', 'Version date parsed failure'), ('pdf_error', 'Failed to parse PDF'), ('link_error', 'Could not generate PDF link')], default=None, max_length=30),
        ),
    ]
