# Generated by Django 4.2 on 2023-04-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_comments_parsingerror_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsingerror',
            old_name='errorType',
            new_name='error_type',
        ),
    ]
