# Generated by Django 4.2 on 2023-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_parsingerror_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingerror',
            name='source_product_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
