# Generated by Django 4.2 on 2023-04-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_druglabel_source'),
        ('data', '0012_parsingerror_source_product_number'),
    ]

    operations = [
    ]
