# Generated by Django 4.2 on 2023-05-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_rename_section_name_productsection_agency_section_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsection',
            name='agency_section_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
