# Generated by Django 4.0.2 on 2022-04-22 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_productsection_section_text'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(max_length=255, upload_to='my_labels/')),
                ('is_successfully_parsed', models.BooleanField(db_index=True, default=False)),
                ('drug_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.druglabel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
