MAX_LENGTH_SEARCH_RESULT_DISPLAY = 200

TYPE_AHEAD_MAPPING = {
    "manufacturers": [
        "bayer",
        "gsk",
        "pfizer",
    ],
    "generic_name": [
        "hola",
        "como",
        "stas",
    ],
    "active_ingredients": [
        "bcaa",
        "creatine",
        "acetaminophen",
    ],
    "marketing_category": [
        "Cosmetic",
        "Dietary Supplement",
        "Drug for Further Processing",
        "Emergency Use Authorization",
        "Exempt device",
    ],
    "country": [
        "Austria",
        "Belgium",
        "Bulgaria",
        "Croatia",
        "Republic of Cyprus",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hungary",
        "Ireland",
        "Italy",
        "Latvia",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Netherlands",
        "Poland",
        "Portugal",
        "Romania",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
    ],
    "generic_name": [
        "alendronate tablet",
        "acyclovir capsule",
        "acyclovir tablet",
        "albuterol inhalation solution",
        "albuterol sulfate",
        "alclometasone dipropionate cream",
        "alfuzosin hcl",
        "alitretinoin",
        "allopurinol tablet",
        "alprazolam",
    ],
    "brand_name": [
        "Fosamax",
        "Zovirax",
        "Zovirax",
        "Albuterol Inhalation Solution",
        "ProAir RespiClick Powder Inhaler",
        "Aclovate",
        "Uroxatral",
        "Panretin gel",
        "Zyloprim",
        "Xanax",
    ],
    "ndc": [
        "0002-0800",
        "0002-1200",
        "0002-1210",
        "0002-1433",
        "0002-1434",
        "0002-1436",
        "0002-1445",
        "0002-2236",
    ],
}
