# Generated by Django 4.0.2 on 2023-02-24 21:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_productsection_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsection',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='productsection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='data_produc_search__727e3f_gin'),
        ),
    ]
