name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v3
 
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        continue-on-error: true
        
      - name: Deploy to AWS CloudFormation
        if: contains(github.event.head_commit.message, 'deploy_main')
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: test
          capabilities: CAPABILITY_NAMED_IAM
          template: deploy_main.yaml
        continue-on-error: true

    
      - name: Run a multi-line script
        run: |
          whoami
          pwd
          cd /etc
          ls
        continue-on-error: true
